version: "3"
services:
  apiflask:
    build: .
    container_name: api_flask
    restart: always
    env_file:
     - .env
    ports:
       - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/src
    working_dir: /src
    command: python src/app.py
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

